#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CineGooseberry_01_BP

#include "Basic.hpp"

#include "CineGooseberry_01_BP_classes.hpp"
#include "CineGooseberry_01_BP_parameters.hpp"


namespace SDK
{

// Function CineGooseberry-01_BP.CineGooseberry-01_BP_C.GetFuttermanAnimation
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class USkeletalMeshComponent*           NewParam                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UAnimSequence*                    Animation                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ACineGooseberry_01_BP_C::GetFuttermanAnimation(class USkeletalMeshComponent* NewParam, class UAnimSequence** Animation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CineGooseberry-01_BP_C", "GetFuttermanAnimation");

	Params::CineGooseberry_01_BP_C_GetFuttermanAnimation Parms{};

	Parms.NewParam = NewParam;

	UObject::ProcessEvent(Func, &Parms);

	if (Animation != nullptr)
		*Animation = Parms.Animation;
}


// Function CineGooseberry-01_BP.CineGooseberry-01_BP_C.SetDrillOn
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    drillOn                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// float                                   DrillRate                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ACineGooseberry_01_BP_C::SetDrillOn(bool drillOn, float DrillRate)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CineGooseberry-01_BP_C", "SetDrillOn");

	Params::CineGooseberry_01_BP_C_SetDrillOn Parms{};

	Parms.drillOn = drillOn;
	Parms.DrillRate = DrillRate;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CineGooseberry-01_BP.CineGooseberry-01_BP_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ACineGooseberry_01_BP_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CineGooseberry-01_BP_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CineGooseberry-01_BP.CineGooseberry-01_BP_C.GetCineFaceAnimBP
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class UCineFace_AnimBP_C*               CineFaceAnimBP                                         (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ACineGooseberry_01_BP_C::GetCineFaceAnimBP(class UCineFace_AnimBP_C** CineFaceAnimBP)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CineGooseberry-01_BP_C", "GetCineFaceAnimBP");

	Params::CineGooseberry_01_BP_C_GetCineFaceAnimBP Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (CineFaceAnimBP != nullptr)
		*CineFaceAnimBP = Parms.CineFaceAnimBP;
}


// Function CineGooseberry-01_BP.CineGooseberry-01_BP_C.GetPoseAsset
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UPoseAsset*                       PoseAsset                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ACineGooseberry_01_BP_C::GetPoseAsset(class UPoseAsset** PoseAsset)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CineGooseberry-01_BP_C", "GetPoseAsset");

	Params::CineGooseberry_01_BP_C_GetPoseAsset Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (PoseAsset != nullptr)
		*PoseAsset = Parms.PoseAsset;
}

}

