#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ConsumingProgressWidget

#include "Basic.hpp"

#include "ConsumingProgressWidget_classes.hpp"
#include "ConsumingProgressWidget_parameters.hpp"


namespace SDK
{

// Function ConsumingProgressWidget.ConsumingProgressWidget_C.ExecuteUbergraph_ConsumingProgressWidget
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UConsumingProgressWidget_C::ExecuteUbergraph_ConsumingProgressWidget(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConsumingProgressWidget_C", "ExecuteUbergraph_ConsumingProgressWidget");

	Params::ConsumingProgressWidget_C_ExecuteUbergraph_ConsumingProgressWidget Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ConsumingProgressWidget.ConsumingProgressWidget_C.OnStatusChanged
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EPlayerActionStatus                     status                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UConsumingProgressWidget_C::OnStatusChanged(EPlayerActionStatus status)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConsumingProgressWidget_C", "OnStatusChanged");

	Params::ConsumingProgressWidget_C_OnStatusChanged Parms{};

	Parms.status = status;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ConsumingProgressWidget.ConsumingProgressWidget_C.Event_Hide
// (Event, Public, BlueprintEvent)

void UConsumingProgressWidget_C::Event_Hide()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConsumingProgressWidget_C", "Event_Hide");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ConsumingProgressWidget.ConsumingProgressWidget_C.OnProgressChanged
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   newProgress                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EActionProgressContext                  Context                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UConsumingProgressWidget_C::OnProgressChanged(float newProgress, EActionProgressContext Context)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConsumingProgressWidget_C", "OnProgressChanged");

	Params::ConsumingProgressWidget_C_OnProgressChanged Parms{};

	Parms.newProgress = newProgress;
	Parms.Context = Context;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ConsumingProgressWidget.ConsumingProgressWidget_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UConsumingProgressWidget_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConsumingProgressWidget_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ConsumingProgressWidget.ConsumingProgressWidget_C.UpdateProgress
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   progress_0                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UConsumingProgressWidget_C::UpdateProgress(float progress_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConsumingProgressWidget_C", "UpdateProgress");

	Params::ConsumingProgressWidget_C_UpdateProgress Parms{};

	Parms.progress_0 = progress_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ConsumingProgressWidget.ConsumingProgressWidget_C.UpdateTextures
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UConsumingProgressWidget_C::UpdateTextures()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConsumingProgressWidget_C", "UpdateTextures");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ConsumingProgressWidget.ConsumingProgressWidget_C.ShouldShow
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UConsumingProgressWidget_C::ShouldShow() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConsumingProgressWidget_C", "ShouldShow");

	Params::ConsumingProgressWidget_C_ShouldShow Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

