#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: gooseberry_AnimBP

#include "Basic.hpp"

#include "grunt_AnimBP_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass gooseberry_AnimBP.gooseberry_AnimBP_C
// 0x0000 (0xC6C0 - 0xC6C0)
class Ugooseberry_AnimBP_C final : public Ugrunt_AnimBP_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"gooseberry_AnimBP_C">();
	}
	static class Ugooseberry_AnimBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<Ugooseberry_AnimBP_C>();
	}
};
static_assert(alignof(Ugooseberry_AnimBP_C) == 0x000010, "Wrong alignment on Ugooseberry_AnimBP_C");
static_assert(sizeof(Ugooseberry_AnimBP_C) == 0x00C6C0, "Wrong size on Ugooseberry_AnimBP_C");

}

