#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HUDGameMessages

#include "Basic.hpp"

#include "HUDGameMessages_classes.hpp"
#include "HUDGameMessages_parameters.hpp"


namespace SDK
{

// Function HUDGameMessages.HUDGameMessages_C.ExecuteUbergraph_HUDGameMessages
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UHUDGameMessages_C::ExecuteUbergraph_HUDGameMessages(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HUDGameMessages_C", "ExecuteUbergraph_HUDGameMessages");

	Params::HUDGameMessages_C_ExecuteUbergraph_HUDGameMessages Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function HUDGameMessages.HUDGameMessages_C.Event_Hide
// (Event, Public, BlueprintEvent)

void UHUDGameMessages_C::Event_Hide()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HUDGameMessages_C", "Event_Hide");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HUDGameMessages.HUDGameMessages_C.Event_OnHudModeChanged
// (Event, Public, BlueprintEvent)
// Parameters:
// EHudMode                                newHudMode                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UHUDGameMessages_C::Event_OnHudModeChanged(EHudMode newHudMode)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HUDGameMessages_C", "Event_OnHudModeChanged");

	Params::HUDGameMessages_C_Event_OnHudModeChanged Parms{};

	Parms.newHudMode = newHudMode;

	UObject::ProcessEvent(Func, &Parms);
}


// Function HUDGameMessages.HUDGameMessages_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UHUDGameMessages_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HUDGameMessages_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HUDGameMessages.HUDGameMessages_C.ShowMessage
// (BlueprintCallable, BlueprintEvent)

void UHUDGameMessages_C::ShowMessage()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HUDGameMessages_C", "ShowMessage");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HUDGameMessages.HUDGameMessages_C.Event_Show
// (Event, Public, BlueprintEvent)

void UHUDGameMessages_C::Event_Show()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HUDGameMessages_C", "Event_Show");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HUDGameMessages.HUDGameMessages_C.OnShowGameMessage_Event_0
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText                             gameMessage                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// EGameMessageCategory                    messageCategory                                        (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FGameMessageAudioParams          audioParams                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)

void UHUDGameMessages_C::OnShowGameMessage_Event_0(const class FText& gameMessage, const EGameMessageCategory messageCategory, const struct FGameMessageAudioParams& audioParams)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HUDGameMessages_C", "OnShowGameMessage_Event_0");

	Params::HUDGameMessages_C_OnShowGameMessage_Event_0 Parms{};

	Parms.gameMessage = std::move(gameMessage);
	Parms.messageCategory = messageCategory;
	Parms.audioParams = std::move(audioParams);

	UObject::ProcessEvent(Func, &Parms);
}


// Function HUDGameMessages.HUDGameMessages_C.Finished_1D4430144A0F9FAAAB764FB894A8E54F
// (BlueprintCallable, BlueprintEvent)

void UHUDGameMessages_C::Finished_1D4430144A0F9FAAAB764FB894A8E54F()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HUDGameMessages_C", "Finished_1D4430144A0F9FAAAB764FB894A8E54F");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HUDGameMessages.HUDGameMessages_C.InitializeMessage
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText                             Message_0                                              (BlueprintVisible, BlueprintReadOnly, Parm)
// EGameMessageCategory                    messageCategory                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FGameMessageAudioParams          audioParams                                            (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)

void UHUDGameMessages_C::InitializeMessage(const class FText& Message_0, EGameMessageCategory messageCategory, const struct FGameMessageAudioParams& audioParams)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HUDGameMessages_C", "InitializeMessage");

	Params::HUDGameMessages_C_InitializeMessage Parms{};

	Parms.Message_0 = std::move(Message_0);
	Parms.messageCategory = messageCategory;
	Parms.audioParams = std::move(audioParams);

	UObject::ProcessEvent(Func, &Parms);
}


// Function HUDGameMessages.HUDGameMessages_C.ShouldShow
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UHUDGameMessages_C::ShouldShow() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HUDGameMessages_C", "ShouldShow");

	Params::HUDGameMessages_C_ShouldShow Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

