#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: IntermediateObjectiveTextWidget

#include "Basic.hpp"

#include "IntermediateObjectiveTextWidget_classes.hpp"
#include "IntermediateObjectiveTextWidget_parameters.hpp"


namespace SDK
{

// Function IntermediateObjectiveTextWidget.IntermediateObjectiveTextWidget_C.UpdateStatusAndText
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    status                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class FText                             Text                                                   (BlueprintVisible, BlueprintReadOnly, Parm)

void UIntermediateObjectiveTextWidget_C::UpdateStatusAndText(bool status, const class FText& Text)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("IntermediateObjectiveTextWidget_C", "UpdateStatusAndText");

	Params::IntermediateObjectiveTextWidget_C_UpdateStatusAndText Parms{};

	Parms.status = status;
	Parms.Text = std::move(Text);

	UObject::ProcessEvent(Func, &Parms);
}

}

