#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MainObjectiveWidget

#include "Basic.hpp"

#include "MainObjectiveWidget_classes.hpp"
#include "MainObjectiveWidget_parameters.hpp"


namespace SDK
{

// Function MainObjectiveWidget.MainObjectiveWidget_C.ExecuteUbergraph_MainObjectiveWidget
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMainObjectiveWidget_C::ExecuteUbergraph_MainObjectiveWidget(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainObjectiveWidget_C", "ExecuteUbergraph_MainObjectiveWidget");

	Params::MainObjectiveWidget_C_ExecuteUbergraph_MainObjectiveWidget Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainObjectiveWidget.MainObjectiveWidget_C.Event_ProgressChanged
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// class ARBBaseObjectiveCoordinator*      coordinator                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   progress                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    isPositiveProgress                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class FText                             objectiveText                                          (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// bool                                    bForceShow                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UMainObjectiveWidget_C::Event_ProgressChanged(class ARBBaseObjectiveCoordinator* coordinator, float progress, bool isPositiveProgress, const class FText& objectiveText, bool bForceShow)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainObjectiveWidget_C", "Event_ProgressChanged");

	Params::MainObjectiveWidget_C_Event_ProgressChanged Parms{};

	Parms.coordinator = coordinator;
	Parms.progress = progress;
	Parms.isPositiveProgress = isPositiveProgress;
	Parms.objectiveText = std::move(objectiveText);
	Parms.bForceShow = bForceShow;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainObjectiveWidget.MainObjectiveWidget_C.Event_Completed
// (Event, Protected, BlueprintEvent)

void UMainObjectiveWidget_C::Event_Completed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainObjectiveWidget_C", "Event_Completed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainObjectiveWidget.MainObjectiveWidget_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// struct FGeometry                        MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMainObjectiveWidget_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainObjectiveWidget_C", "Tick");

	Params::MainObjectiveWidget_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainObjectiveWidget.MainObjectiveWidget_C.Event_IsMakingPositiveProgress
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    isMakingPositiveProgress_0                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UMainObjectiveWidget_C::Event_IsMakingPositiveProgress(bool isMakingPositiveProgress_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainObjectiveWidget_C", "Event_IsMakingPositiveProgress");

	Params::MainObjectiveWidget_C_Event_IsMakingPositiveProgress Parms{};

	Parms.isMakingPositiveProgress_0 = isMakingPositiveProgress_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainObjectiveWidget.MainObjectiveWidget_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UMainObjectiveWidget_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainObjectiveWidget_C", "PreConstruct");

	Params::MainObjectiveWidget_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainObjectiveWidget.MainObjectiveWidget_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UMainObjectiveWidget_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainObjectiveWidget_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainObjectiveWidget.MainObjectiveWidget_C.Finished_8A3EC16D4EBA343192A93F85CA6E35E3
// (BlueprintCallable, BlueprintEvent)

void UMainObjectiveWidget_C::Finished_8A3EC16D4EBA343192A93F85CA6E35E3()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainObjectiveWidget_C", "Finished_8A3EC16D4EBA343192A93F85CA6E35E3");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainObjectiveWidget.MainObjectiveWidget_C.SetIsMakingPositiveProgress
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    isMakingPositiveProgress_0                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UMainObjectiveWidget_C::SetIsMakingPositiveProgress(bool isMakingPositiveProgress_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainObjectiveWidget_C", "SetIsMakingPositiveProgress");

	Params::MainObjectiveWidget_C_SetIsMakingPositiveProgress Parms{};

	Parms.isMakingPositiveProgress_0 = isMakingPositiveProgress_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainObjectiveWidget.MainObjectiveWidget_C.SetProgressRatio
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   ratio                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMainObjectiveWidget_C::SetProgressRatio(float ratio)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainObjectiveWidget_C", "SetProgressRatio");

	Params::MainObjectiveWidget_C_SetProgressRatio Parms{};

	Parms.ratio = ratio;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainObjectiveWidget.MainObjectiveWidget_C.UpdateIntermediateObjectives
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UMainObjectiveWidget_C::UpdateIntermediateObjectives()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainObjectiveWidget_C", "UpdateIntermediateObjectives");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MainObjectiveWidget.MainObjectiveWidget_C.GetFadeInAnimation
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWidgetAnimation*                 FadeInAnimation                                        (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMainObjectiveWidget_C::GetFadeInAnimation(class UWidgetAnimation** FadeInAnimation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainObjectiveWidget_C", "GetFadeInAnimation");

	Params::MainObjectiveWidget_C_GetFadeInAnimation Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (FadeInAnimation != nullptr)
		*FadeInAnimation = Parms.FadeInAnimation;
}


// Function MainObjectiveWidget.MainObjectiveWidget_C.Initialize
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ARBBaseObjectiveCoordinator*      coordinator                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMainObjectiveWidget_C::Initialize(class ARBBaseObjectiveCoordinator* coordinator)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainObjectiveWidget_C", "Initialize");

	Params::MainObjectiveWidget_C_Initialize Parms{};

	Parms.coordinator = coordinator;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MainObjectiveWidget.MainObjectiveWidget_C.GetRemoveAnimation
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class UWidgetAnimation*                 RemoveAnimation_0                                      (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMainObjectiveWidget_C::GetRemoveAnimation(class UWidgetAnimation** RemoveAnimation_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainObjectiveWidget_C", "GetRemoveAnimation");

	Params::MainObjectiveWidget_C_GetRemoveAnimation Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (RemoveAnimation_0 != nullptr)
		*RemoveAnimation_0 = Parms.RemoveAnimation_0;
}


// Function MainObjectiveWidget.MainObjectiveWidget_C.ShouldShow
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UMainObjectiveWidget_C::ShouldShow() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MainObjectiveWidget_C", "ShouldShow");

	Params::MainObjectiveWidget_C_ShouldShow Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

