#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: player_3P_AnimBP

#include "Basic.hpp"

#include "player_3P_AnimBP_classes.hpp"
#include "player_3P_AnimBP_parameters.hpp"


namespace SDK
{

// Function player_3P_AnimBP.player_3P_AnimBP_C.ExecuteUbergraph_player_3P_AnimBP
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uplayer_3P_AnimBP_C::ExecuteUbergraph_player_3P_AnimBP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("player_3P_AnimBP_C", "ExecuteUbergraph_player_3P_AnimBP");

	Params::player_3P_AnimBP_C_ExecuteUbergraph_player_3P_AnimBP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function player_3P_AnimBP.player_3P_AnimBP_C.AnimNotify_NoCombine
// (BlueprintCallable, BlueprintEvent)

void Uplayer_3P_AnimBP_C::AnimNotify_NoCombine()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("player_3P_AnimBP_C", "AnimNotify_NoCombine");

	UObject::ProcessEvent(Func, nullptr);
}


// Function player_3P_AnimBP.player_3P_AnimBP_C.AnimNotify_StopPush_Left
// (BlueprintCallable, BlueprintEvent)

void Uplayer_3P_AnimBP_C::AnimNotify_StopPush_Left()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("player_3P_AnimBP_C", "AnimNotify_StopPush_Left");

	UObject::ProcessEvent(Func, nullptr);
}


// Function player_3P_AnimBP.player_3P_AnimBP_C.AnimNotify_StartPush_Left
// (BlueprintCallable, BlueprintEvent)

void Uplayer_3P_AnimBP_C::AnimNotify_StartPush_Left()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("player_3P_AnimBP_C", "AnimNotify_StartPush_Left");

	UObject::ProcessEvent(Func, nullptr);
}


// Function player_3P_AnimBP.player_3P_AnimBP_C.AnimNotify_IdleBreaker
// (BlueprintCallable, BlueprintEvent)

void Uplayer_3P_AnimBP_C::AnimNotify_IdleBreaker()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("player_3P_AnimBP_C", "AnimNotify_IdleBreaker");

	UObject::ProcessEvent(Func, nullptr);
}


// Function player_3P_AnimBP.player_3P_AnimBP_C.AnimNotify_Alive
// (BlueprintCallable, BlueprintEvent)

void Uplayer_3P_AnimBP_C::AnimNotify_Alive()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("player_3P_AnimBP_C", "AnimNotify_Alive");

	UObject::ProcessEvent(Func, nullptr);
}


// Function player_3P_AnimBP.player_3P_AnimBP_C.AnimNotify_Dead
// (BlueprintCallable, BlueprintEvent)

void Uplayer_3P_AnimBP_C::AnimNotify_Dead()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("player_3P_AnimBP_C", "AnimNotify_Dead");

	UObject::ProcessEvent(Func, nullptr);
}


// Function player_3P_AnimBP.player_3P_AnimBP_C.BlueprintUpdateAnimation
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaTimeX                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uplayer_3P_AnimBP_C::BlueprintUpdateAnimation(float DeltaTimeX)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("player_3P_AnimBP_C", "BlueprintUpdateAnimation");

	Params::player_3P_AnimBP_C_BlueprintUpdateAnimation Parms{};

	Parms.DeltaTimeX = DeltaTimeX;

	UObject::ProcessEvent(Func, &Parms);
}


// Function player_3P_AnimBP.player_3P_AnimBP_C.AnimNotify_IsBack
// (BlueprintCallable, BlueprintEvent)

void Uplayer_3P_AnimBP_C::AnimNotify_IsBack()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("player_3P_AnimBP_C", "AnimNotify_IsBack");

	UObject::ProcessEvent(Func, nullptr);
}


// Function player_3P_AnimBP.player_3P_AnimBP_C.AnimNotify_IsIdle
// (BlueprintCallable, BlueprintEvent)

void Uplayer_3P_AnimBP_C::AnimNotify_IsIdle()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("player_3P_AnimBP_C", "AnimNotify_IsIdle");

	UObject::ProcessEvent(Func, nullptr);
}


// Function player_3P_AnimBP.player_3P_AnimBP_C.AnimNotify_IsGone
// (BlueprintCallable, BlueprintEvent)

void Uplayer_3P_AnimBP_C::AnimNotify_IsGone()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("player_3P_AnimBP_C", "AnimNotify_IsGone");

	UObject::ProcessEvent(Func, nullptr);
}


// Function player_3P_AnimBP.player_3P_AnimBP_C.ShouldIgnoreLookAround
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool Uplayer_3P_AnimBP_C::ShouldIgnoreLookAround()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("player_3P_AnimBP_C", "ShouldIgnoreLookAround");

	Params::player_3P_AnimBP_C_ShouldIgnoreLookAround Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function player_3P_AnimBP.player_3P_AnimBP_C.ToggleAFK
// (Public, BlueprintCallable, BlueprintEvent)

void Uplayer_3P_AnimBP_C::ToggleAFK()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("player_3P_AnimBP_C", "ToggleAFK");

	UObject::ProcessEvent(Func, nullptr);
}


// Function player_3P_AnimBP.player_3P_AnimBP_C.IsValidUpperBodyAnimationForLookAt
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class ARBPawn*                          Player                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bValid                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void Uplayer_3P_AnimBP_C::IsValidUpperBodyAnimationForLookAt(class ARBPawn* Player, bool* bValid)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("player_3P_AnimBP_C", "IsValidUpperBodyAnimationForLookAt");

	Params::player_3P_AnimBP_C_IsValidUpperBodyAnimationForLookAt Parms{};

	Parms.Player = Player;

	UObject::ProcessEvent(Func, &Parms);

	if (bValid != nullptr)
		*bValid = Parms.bValid;
}


// Function player_3P_AnimBP.player_3P_AnimBP_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void Uplayer_3P_AnimBP_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("player_3P_AnimBP_C", "AnimGraph");

	Params::player_3P_AnimBP_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}

}

