#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: player_female_3P_AnimBP

#include "Basic.hpp"

#include "player_3P_AnimBP_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass player_female_3P_AnimBP.player_female_3P_AnimBP_C
// 0x0000 (0x11190 - 0x11190)
class Uplayer_female_3P_AnimBP_C final : public Uplayer_3P_AnimBP_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"player_female_3P_AnimBP_C">();
	}
	static class Uplayer_female_3P_AnimBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<Uplayer_female_3P_AnimBP_C>();
	}
};
static_assert(alignof(Uplayer_female_3P_AnimBP_C) == 0x000010, "Wrong alignment on Uplayer_female_3P_AnimBP_C");
static_assert(sizeof(Uplayer_female_3P_AnimBP_C) == 0x011190, "Wrong size on Uplayer_female_3P_AnimBP_C");

}

