#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SecondaryObjectiveWidget

#include "Basic.hpp"

#include "SecondaryObjectiveWidget_classes.hpp"
#include "SecondaryObjectiveWidget_parameters.hpp"


namespace SDK
{

// Function SecondaryObjectiveWidget.SecondaryObjectiveWidget_C.ExecuteUbergraph_SecondaryObjectiveWidget
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USecondaryObjectiveWidget_C::ExecuteUbergraph_SecondaryObjectiveWidget(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SecondaryObjectiveWidget_C", "ExecuteUbergraph_SecondaryObjectiveWidget");

	Params::SecondaryObjectiveWidget_C_ExecuteUbergraph_SecondaryObjectiveWidget Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SecondaryObjectiveWidget.SecondaryObjectiveWidget_C.Event_ProgressChanged
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// class ARBBaseObjectiveCoordinator*      coordinator                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   progress                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    isPositiveProgress                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class FText                             objectiveText_0                                        (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// bool                                    bForceShow                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void USecondaryObjectiveWidget_C::Event_ProgressChanged(class ARBBaseObjectiveCoordinator* coordinator, float progress, bool isPositiveProgress, const class FText& objectiveText_0, bool bForceShow)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SecondaryObjectiveWidget_C", "Event_ProgressChanged");

	Params::SecondaryObjectiveWidget_C_Event_ProgressChanged Parms{};

	Parms.coordinator = coordinator;
	Parms.progress = progress;
	Parms.isPositiveProgress = isPositiveProgress;
	Parms.objectiveText_0 = std::move(objectiveText_0);
	Parms.bForceShow = bForceShow;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SecondaryObjectiveWidget.SecondaryObjectiveWidget_C.HandleVisibilityEvent
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsVisible_0                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void USecondaryObjectiveWidget_C::HandleVisibilityEvent(bool IsVisible_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SecondaryObjectiveWidget_C", "HandleVisibilityEvent");

	Params::SecondaryObjectiveWidget_C_HandleVisibilityEvent Parms{};

	Parms.IsVisible_0 = IsVisible_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SecondaryObjectiveWidget.SecondaryObjectiveWidget_C.GetFadeInAnimation
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWidgetAnimation*                 FadeInAnimation                                        (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USecondaryObjectiveWidget_C::GetFadeInAnimation(class UWidgetAnimation** FadeInAnimation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SecondaryObjectiveWidget_C", "GetFadeInAnimation");

	Params::SecondaryObjectiveWidget_C_GetFadeInAnimation Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (FadeInAnimation != nullptr)
		*FadeInAnimation = Parms.FadeInAnimation;
}


// Function SecondaryObjectiveWidget.SecondaryObjectiveWidget_C.SetCompleted
// (Public, BlueprintCallable, BlueprintEvent)

void USecondaryObjectiveWidget_C::SetCompleted()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SecondaryObjectiveWidget_C", "SetCompleted");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SecondaryObjectiveWidget.SecondaryObjectiveWidget_C.Initialize
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ARBBaseObjectiveCoordinator*      coordinator                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USecondaryObjectiveWidget_C::Initialize(class ARBBaseObjectiveCoordinator* coordinator)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SecondaryObjectiveWidget_C", "Initialize");

	Params::SecondaryObjectiveWidget_C_Initialize Parms{};

	Parms.coordinator = coordinator;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SecondaryObjectiveWidget.SecondaryObjectiveWidget_C.ShouldShow
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool USecondaryObjectiveWidget_C::ShouldShow() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SecondaryObjectiveWidget_C", "ShouldShow");

	Params::SecondaryObjectiveWidget_C_ShouldShow Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

